- hosts: all
  sudo: yes

  tasks:
  - name: Install Packages
    apt: name={{ item }} update_cache=yes state=present
    with_items:
      - tomcat 
      - libapache2-mod-php
      - git
      - curl


  # - name: Git Clone Repo
  #   git: repo=https://github.com/********/spinnaker-packer-ansible-php-azure-demo.git dest=/opt/phpapp update=yes force=yes accept_hostkey=yes 
  #   register: git_finished

  - name: copy D_worker_nurl.war
    sudo: yes
    copy: src=/D_worker_nurl.war  dest=/usr/share/tomcat/webapps/D_worker_nurl.war mode=644 
    
  - name: copy D_worker_request.war
    sudo: yes
    copy: src=/tmp/D_worker_request.war  dest=/usr/share/tomcat/webapps/D_worker_request.war mode=644 
    

  - name: copy application.yaml.hk
    sudo: yes
    copy: src=/tmp/application.yaml.hk  dest=/home/tomcat/DESU/application.yaml.hk mode=644 
    

  - name: copy configMessage.json.hk
    sudo: yes
    copy: src=/tmp/configMessage.json.hk  dest=/home/tomcat/DESU/webapps/application.yaml.hk 
    notify: Restart tomcat
  

  handlers:
  - name: Restart tomcat
    service: name=tomcat state=restarted