---
- hosts: all
  sudo: yes
  
  tasks:
  - name: Install Packages
    yum: name={{ item }} update_cache=yes state=present
    with_items:
      - tomcat 
      - git
      - curl

  - name: Create tomcat directory
    file: path=/home/tomcat state=directory owner=tomcat group=tomcat mode=0755

  - name: Created DESU directory
    file:  path=/home/tomcat/DESU state=directory owner=tomcat group=tomcat mode=0755
  
  - user: name=tomcat home=/home/tomcat group=tomcat
    
  - name: copy D_worker_nurl.war
    sudo: yes
    copy: src=/tmp/D_worker_nurl.war  dest=/usr/share/tomcat/webapps/D_worker_nurl.war owner=tomcat group=tomcat mode=644 
    
  - name: copy D_worker_request.war
    sudo: yes
    copy: src=/tmp/D_worker_request.war  dest=/usr/share/tomcat/webapps/D_worker_request.war owner=tomcat group=tomcat mode=644 
    

  - name: copy application.yaml
    sudo: yes
    copy: src=/tmp/application.yaml  dest=/home/tomcat/DESU/application.yaml owner=tomcat group=tomcat mode=644 
  
  - name: copy configMessage.json
    sudo: yes
    copy: src=/tmp/configMessage.json  dest=/home/tomcat/DESU/configMessage.json owner=tomcat group=tomcat mode=644
    notify: Start tomcat

  
  handlers:
  - name: Start tomcat
    service: name=tomcat state=started enabled=yes

      